-- AlterTable
ALTER TABLE "Cliente" ADD COLUMN     "saldoInicial" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "saldoInicialPagado" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Proveedor" ADD COLUMN     "saldoInicialCxp" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "saldoInicialCxpPagado" DOUBLE PRECISION NOT NULL DEFAULT 0;

